# Hosts Private IPs
nfs-server ansible_host=<private ip>
db-server ansible_host=<private ip>
web-server1 ansible_host=<private ip>
web-server2 ansible_host=<private ip>
alb-server ansible_host=<private ip>

#Groups
[nfsgroup]
nfs-server

[dbgroup]
db-server

[webgroup]
web-server1
web-server2

[albgroup]
alb-server

# Group specific variables
[nfsgroup:vars]
ansible_user=ec2-user

[dbgroup:vars]
ansible_user=ubuntu

[webgroup:vars]
ansible_user=ec2-user

[albgroup:vars]
ansible_user=ubuntu

# All hosts
[devops_tooling:children]
dbgroup
nfsgroup
webgroup
albgroup

# All hosts variables
[devops_tooling:vars]
ansible_ssh_private_key_file=~/ansible-config-mgt/DevOpsMasterClass_London.pem

