Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### fedora vm  ####
  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "jacobw/fedora35-arm64"
    fedora.vm.hostname = "fedora"
    fedora.vm.network "private_network", ip: "192.168.56.15"
    # fedora.vm.provider "vmware_desktop" do |vmware|
      # vmware.memory = "1024"
    # end
    # fedora.vm.provision "shell", path: "mysql.sh"  
  end
   
  
### Ubuntu VM ###
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "spox/ubuntu-arm"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.network "private_network", ip: "192.168.56.11"
  # ubuntu.vm.provision "shell", path: "nginx.sh"   
end 

end

